name: fitness_tracker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_generative_ai: ^0.2.0
  shimmer: ^3.0.0
  geocoding: ^2.1.0
  jwt_decode: ^0.3.1

flutter:
  uses-material-design: true 