name: fitness_tracker
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.0.12
  carousel_slider: ^5.0.0
  flutter_native_splash: ^2.3.10
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  table_calendar: ^3.0.9
  fl_chart: ^0.68.0
  intl: ^0.18.1
  logger: ^2.0.1
  get: ^4.6.5
  get_storage: ^2.1.1
  firebase_core: ^3.12.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/onboardingImages/
    - assets/icons/logos/
    - assets/icons/location/
    - assets/images/
    - assets/animations/
    - assets/categories/
    - assets/slider_images/
    - assets/backgrounds/run_background/
    - assets/backgrounds/calendar_background/
    - assets/fonts/
    - assets/icons/logos/splash_logo/
    - assets/icons/app_icons/
    - assets/icons/app_icons/activity_icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Variable.ttf
        - asset: assets/fonts/Nunito-VariableItalic.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/logos/splash_logo/Logo-black.png
  color_dark: "#000000"
  image_dark: assets/icons/logos/splash_logo/Logo-white.png
  android: true
  ios: true
  web: false
  android_12:
    image: assets/icons/logos/splash_logo/Logo-black.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/icons/logos/splash_logo/Logo-white.png
    icon_background_color_dark: "#000000"
  android_gravity: center
  ios_content_mode: center

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logos/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logos/app_logo.png"
  remove_alpha_ios: true
  image_path_ios: "assets/icons/logos/app_logo.png"
  image_path_android: "assets/icons/logos/app_logo.png"
  adaptive_icon_padding: true
  adaptive_icon_padding_android: 0.1