// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrROeWjlMxnvKcLa_dTa9dCrCXQowasGo',
    appId: '1:420533027078:web:5365333d3566dc71b29e87',
    messagingSenderId: '420533027078',
    projectId: 'fitness-tracking-ccf2a',
    authDomain: 'fitness-tracking-ccf2a.firebaseapp.com',
    storageBucket: 'fitness-tracking-ccf2a.firebasestorage.app',
    measurementId: 'G-1684W1TM0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUW7CYXzwWhoFSewB4KvNnY_quW3Q3SV8',
    appId: '1:420533027078:android:ec6e18c7119894bfb29e87',
    messagingSenderId: '420533027078',
    projectId: 'fitness-tracking-ccf2a',
    storageBucket: 'fitness-tracking-ccf2a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf4g3M2BhMjnBYQ0iGeAoZhBD9G7rPn70',
    appId: '1:420533027078:ios:d7a1a7c20ed7771fb29e87',
    messagingSenderId: '420533027078',
    projectId: 'fitness-tracking-ccf2a',
    storageBucket: 'fitness-tracking-ccf2a.firebasestorage.app',
    androidClientId: '420533027078-muor7to6u3oa20ik9vakk0ospijt35te.apps.googleusercontent.com',
    iosClientId: '420533027078-o6us5poaqk9fn10jetipv1ktr2qvfm7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf4g3M2BhMjnBYQ0iGeAoZhBD9G7rPn70',
    appId: '1:420533027078:ios:d7a1a7c20ed7771fb29e87',
    messagingSenderId: '420533027078',
    projectId: 'fitness-tracking-ccf2a',
    storageBucket: 'fitness-tracking-ccf2a.firebasestorage.app',
    androidClientId: '420533027078-muor7to6u3oa20ik9vakk0ospijt35te.apps.googleusercontent.com',
    iosClientId: '420533027078-o6us5poaqk9fn10jetipv1ktr2qvfm7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrROeWjlMxnvKcLa_dTa9dCrCXQowasGo',
    appId: '1:420533027078:web:59de935dc6d5acebb29e87',
    messagingSenderId: '420533027078',
    projectId: 'fitness-tracking-ccf2a',
    authDomain: 'fitness-tracking-ccf2a.firebaseapp.com',
    storageBucket: 'fitness-tracking-ccf2a.firebasestorage.app',
    measurementId: 'G-N6LBSKPJXK',
  );

}